sudo: required
services:
  - docker

before_install:
  - docker build -t sakshirdkar/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sakshirdkar/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Docker-react-env"
  bucket-name: "elasticbeanstalk-us-east-1-317710601505"
  bucket-path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
